version: '3.8'
services:
  # BACKEND (Node.js + Express)
  backend:
    build: ../backend
    ports:
      - "4000:4000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=DieSam2025!
      - DB_NAME=moodtunes
      - JWT_SECRET=d8239f2c1e234f89aaf81239c8123adkfhajshdlkh213
      - SPOTIFY_CLIENT_ID=d26f719218454a13b88ba2f15ee233b7
      - SPOTIFY_CLIENT_SECRET=0b80c77971af4453b245cf8cec605f78
      - SPOTIFY_REDIRECT_URI=https://fbe9-86-127-229-75.ngrok-free.app/callback
      - FRONTEND_URL=http://localhost:5173
      - PORT=4000

  # BASE DE DADES (MySQL)
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=DieSam2025!
      - MYSQL_DATABASE=moodtunes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=DieSam2025!

  # FRONTEND (React + Vite)
  frontend:
    build: ../web
    ports:
      - "5173:5173"
    volumes:
      - ../web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000

volumes:
  mysql_data:
