services:
  backend:
    build: ../backend
    ports:
      - "4000:4000"
    volumes:
      - ../backend:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=DieSam2025!
      - DB_NAME=moodtunes

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DieSam2025!
      MYSQL_DATABASE: moodtunes
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: DieSam2025!

  frontend:
    build: ../web
    ports:
      - "5173:5173"
    volumes:
      - ../web:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://10.102.0.15:4000

volumes:
  mysql_data:
